name: Everett
description: Full Stack Developer
meta_description: "Full Stack Developer Everett"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 5
baseurl: ''
domain_name: 'https://everettjf.github.io'
plugins:
  - jekyll-paginate

# Details for the RSS feed generator
url:            'https://everettjf.github.io'
author:         'Everett'
authorimage: /images/everettjf.png

permalink: /:year/:month/:day/:title/
location: 'Cupertino, CA'
excerpt_separator:  '<!-- more -->'
